<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SilkyNvg\SilkyNvg.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\ShaderCode\paintingShader.frag.glsl" />
      <None Remove="Shaders\ShaderCode\paintingShader.vert.glsl" />
      <None Remove="Shaders\ShaderCode\anchorGeometryShader.frag.glsl" />
      <None Remove="Shaders\ShaderCode\anchorGeometryShader.vert.glsl" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\ShaderCode\shader.frag.glsl" />
      <EmbeddedResource Include="Shaders\ShaderCode\shader.frag.glsl" />
      <None Remove="Shaders\ShaderCode\shader.vert.glsl" />
      <EmbeddedResource Include="Shaders\ShaderCode\shader.vert.glsl" />
    </ItemGroup>

</Project>
