<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SilkyNvg\SilkyNvg.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
      <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\ShaderCode\fragmentGenerationShader.comp.glsl" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\ShaderCode\intersectionFindingShader.comp.glsl" />
      <EmbeddedResource Include="Shaders\ShaderCode\intersectionFindingShader.comp.glsl" />
      <None Remove="Shaders\ShaderCode\fragmentSortingShader.comp.glsl" />
      <EmbeddedResource Include="Shaders\ShaderCode\fragmentSortingShader.comp.glsl" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Shaders\ShaderCode\fragmentGenerationShader.comp.glsl" />
    </ItemGroup>

</Project>
